5 course/Python/19205-Project/accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/',SignUpView.as_view(), name='signup'),
]

5 course/Python/19205-Project/config/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('',include('pages.urls'))
]

5 course/Python/19205-Project/pages/urls.py
from django.urls import path
from .views import (
    PagesListView, 
    PagesDetailView, 
    PagesCreateView,
    PagesUpdateView,
    PagesDeleteView
    )
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('pages/<int:pk>/delete/',PagesDeleteView.as_view(),name = 'post_delete'),
    path('pages/<int:pk>/edit/',PagesUpdateView.as_view(),name = 'post_edit'),
    path('pages/new/',PagesCreateView.as_view(), name="post_new"),
    path('pages/<int:pk>/',PagesDetailView.as_view(),name = 'post_detail'),
    path('',PagesListView.as_view(),name = 'home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

5 course/Python/19205-Project/accounts/models.py
from django.db import models

# Create your models here.

5 course/Python/19205-Project/pages/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Pages(models.Model):
    CATEGORY_CHOICES = [
        ('COOKING',"Cooking"),
        ('TRAVEL', 'Travel'),
        ('FASHION', 'Fashion'),
        ('TECHNOLOGY', 'Technology'),
        ('EDUCATION', 'Education'),
        ('ART', 'Art'),
    ]
    title = models.CharField(max_length = 200)
    author = models.ForeignKey(
        'auth.User',
        on_delete = models.CASCADE,
    )
    body = models.TextField()
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, blank=True, null=True)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


    

5 course/Python/19205-Project/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

5 course/Python/19205-Project/pages/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Pages
# Create your views here.

class PagesListView(ListView):
    model = Pages
    template_name = 'home.html'

class PagesDetailView(DetailView):
    model = Pages
    template_name = 'post_detail.html'

class PagesCreateView(CreateView):
    model = Pages
    template_name = 'post_new.html'
    fields = ['title','author','body','image', 'category']

class PagesUpdateView(UpdateView):
    model = Pages
    template_name = 'post_edit.html'
    fields = ['title','body','image','category']

class PagesDeleteView(DeleteView):
    model = Pages
    template_name = 'post_delete.html'
    success_url = reverse_lazy('home')

5 course/Python/19205-Project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <link rel="stylesheet" href="https://fonts.googlepis.com/css?family=Source+Sans+Pro:400">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <div>
        <header>
            <div class="nav-left">
                <h1><a href="{% url 'home' %}"> Django blog</a></h1>
            </div>
            <div class="nav-right">
                <a href="{% url 'post_new' %}">+ New Blog Post</a>
            </div>
        </header>
        {% if user.is_authenticated %}
            <p>Hello, {{ user.username }}</p>
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Log out</button>
            </form>
        {% else %}
            <p>You are not logged in.</p>
            <a href="{% url 'login' %}">Log in</a>
        {% endif %}
    {% block content %}
    {% endblock content %}
    </div>
</body>
</html>

5 course/Python/19205-Project/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/grid.css' %}">
</head>
<div class="pages-grid">
    {% for pages in pages_list %}
        <div class="pages-entry">
            <h2><a href="{% url 'post_detail' pages.pk %}">{{pages.title}}</a></h2>
            {% if pages.category %}
                <h6>{{ pages.category }}</h6>
            {% endif %}
            {% if pages.image %}
            <img src="{{pages.image.url}}" alt="Image" class="image-thumbnail" >
            {% endif %}
            <p>{{pages.body}}</p>
        </div>
    {% endfor %}
</div>
{% endblock content %}

5 course/Python/19205-Project/templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete post</h1>
<form action="" method="post">
    {% csrf_token %}
    <p>Ara you sure you want to delete "{{ post.title }}"</p>
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

5 course/Python/19205-Project/templates/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="post-entry">
    <h2>{{ pages.title }}</h2>
    {% if pages.category %}
        <h6>{{ pages.category }}</h6>
    {% endif %}
    {% if pages.image %}
    <img src="{{pages.image.url}}" alt="Image" class="image-thumbnail" style="max-height: 200px;">
    {% else %}
    <img src="{% static 'images/image.jpg' %}" alt="Image" class="image-thumbnail" style="max-height: 200px;">
    {% endif %}
    <p>{{ pages.body }}</p>
</div>

<p><a href="{% url 'post_edit' pages.pk %}"> + Edit Blog Post</a></p>
<p><a href="{% url 'post_delete' pages.pk %}"> + Delete Blog Posts</a></p>

{% endblock content %}

5 course/Python/19205-Project/templates/post_edit.html
{% extends 'base.html' %}
{% block content %}
    <h1>Edit post</h1>
    <form action="{% url 'post_edit' pages.pk %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock content %}

5 course/Python/19205-Project/templates/post_new.html
{% extends 'base.html' %}

{% block content %}
<h1>New post</h1>
<form action="{% url 'post_new' %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}